//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServisWeb.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Marka { get; set; }
        public Nullable<decimal> AlisFiyat { get; set; }
        public Nullable<decimal> SatisFiyat { get; set; }
        public Nullable<short> Stok { get; set; }
        public Nullable<byte> Kategori { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
